version: "3.3"
services:
  nginx:
    build:
      context: ./docker/nginx
    container_name: ace_nginx
    ports:
      - 443:443
    depends_on:
      - frontend

  frontend:
    build:
      context: ./docker/frontend
    container_name: ace_frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./docker/backend
    container_name: ace_backend
    depends_on:
      - pg_init
      - redis

  pg_init:
    build:
      context: ./docker/pg_init
    container_name: ace_pg_init
    depends_on:
      - pg

  pg:
    env_file: ./docker/pg/.env
    image: postgres:12
    container_name: ace_pg
    volumes:
      - pg_home:/var/lib/postgresql/data

  redis:
    build:
      context: ./docker/redis
    container_name: ace_redis
    volumes:
      - redis_home:/data

volumes:
  pg_home:
    external: false
  redis_home:
    external: false
